### ISSUE TITLE
CSS wishlist: Dark mode

### ISSUE THREAD

**Issue by Zash** [xsf/xeps#1009]
Steps to reproduce:
1. Configure a dark-mode theme in your OS
2. Turn off the lights
3. Light some candles
4. Open a XEP in a browser

Expects:
Able to read the XEP and haxxor all night long.

Actual:
Ouch, owie, my eyes!

Suggested solution:

Amend the CSS with something like this:

```css
@media screen and (prefers-color-scheme: dark){
	body {
		background-color: black;
		color: white;
	}
}
```
